- name: Add or modify mysql user
  proxysql_mysql_users:
    login_user: 'admin'
    login_password: "{{ admin_login_password }}"
    username: "{{ username }}"
    password: "{{ username_password }}"
    default_hostgroup: 10
    transaction_persistent: yes
    max_connections: 10000
    state: present
    load_to_runtime: yes
    save_to_disk: yes
  tags: manage_user

- name: Encrypt mysql_users
  proxysql_manage_config:
    login_user: 'admin'
    login_password: "{{ admin_login_password }}"
    action: "SAVE"
    config_settings: "MYSQL USERS"
    direction: "FROM"
    config_layer: "RUNTIME"
  tags: manage_user

- name: Delete mysql user
  proxysql_mysql_users:
    login_user: 'admin'
    login_password: "{{ admin_login_password }}"
    username: "{{ del_username }}"
    state: absent
    load_to_runtime: yes
    save_to_disk: yes
  tags: delete_user